# SPDX-FileCopyrightText: (C) 2024-2025 Temple University <kleinweb@temple.edu>
# SPDX-License-Identifier: CC0-1.0

### https://reuse.software/spec-3.2/#reusetoml

version = 1

[[annotations]]
path = [
  "**.json",
  "**.lock",
  "**.properties",
  "**.yml",
  "**.d.ts",
  "**/.ignore",
  "**/.gitattributes",
  "**/.gitignore",
  "**/.gitkeep",
  "**/pnpm-lock.yaml",
  ".config/org_id",
]
SPDX-FileCopyrightText = "(C) 2024-2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.md", "**.org", "**.txt"]
SPDX-FileCopyrightText = "(C) 2024-2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

[[annotations]]
path = ["packages/brand-assets/**"]
SPDX-FileCopyrightText = "(C) 2024-2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "LicenseRef-TU-Trademark-Policy"

[[annotations]]
path = ["packages/gutenberg-types/src/types/**"]
SPDX-FileCopyrightText = [
  "(C) 2025 Temple University <kleinweb@temple.edu>",
  "(C) 2016-2025 The WordPress Contributors",
]
SPDX-License-Identifier = "GPL-3.0-or-later OR MPL-2.0"
