/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JSONSchemaForWordPressFontCollections {
  /**
   * JSON schema URI for font-collection.json.
   */
  $schema?: string;
  /**
   * Array of font families ready to be installed.
   */
  font_families: {
    /**
     * Font family settings, with added preview property.
     */
    font_family_settings: {
      /**
       * Name of the font family preset, translatable.
       */
      name: string;
      /**
       * Kebab-case unique identifier for the font family preset.
       */
      slug: string;
      /**
       * CSS font-family value.
       */
      fontFamily: string;
      /**
       * URL to a preview image of the font family.
       */
      preview?: string;
      /**
       * Array of font-face definitions.
       */
      fontFace?: FontFace[];
    };
    /**
     * Array of category slugs.
     */
    categories?: string[];
  }[];
}
/**
 * Font face settings, with added preview property.
 */
export interface FontFace {
  /**
   * URL to a preview image of the font.
   */
  preview?: string;
  /**
   * CSS font-family value.
   */
  fontFamily: string;
  /**
   * CSS font-style value.
   */
  fontStyle?: string;
  /**
   * List of available font weights, separated by a space.
   */
  fontWeight?: string | number;
  /**
   * CSS font-display value.
   */
  fontDisplay?: "auto" | "block" | "fallback" | "swap" | "optional";
  /**
   * Paths or URLs to the font files.
   */
  src: string | string[];
  /**
   * CSS font-stretch value.
   */
  fontStretch?: string;
  /**
   * CSS ascent-override value.
   */
  ascentOverride?: string;
  /**
   * CSS descent-override value.
   */
  descentOverride?: string;
  /**
   * CSS font-variant value.
   */
  fontVariant?: string;
  /**
   * CSS font-feature-settings value.
   */
  fontFeatureSettings?: string;
  /**
   * CSS font-variation-settings value.
   */
  fontVariationSettings?: string;
  /**
   * CSS line-gap-override value.
   */
  lineGapOverride?: string;
  /**
   * CSS size-adjust value.
   */
  sizeAdjust?: string;
  /**
   * CSS unicode-range value.
   */
  unicodeRange?: string;
}
