/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JSONSchemaForWordPressWpEnvConfigurationFiles = WpEnvProperties & {
  $schema?: string;
  /**
   * The key env is available to override any of the above options on an individual-environment basis.
   */
  env?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z]".
     */
    [k: string]: WpEnvProperties & {
      [k: string]: unknown;
    };
  };
  /**
   * The port number for the test site. You'll access the instance through the port: http://localhost:8889
   */
  testsPort?: number;
  /**
   * Mapping of commands that should be executed at certain points in the lifecycle.
   */
  lifecycleScripts?: {
    /**
     * Runs after wp-env start has finished setting up the environment.
     */
    afterStart?: string;
    /**
     * Runs after wp-env clean has finished cleaning the environment.
     */
    afterClean?: string;
    /**
     * Runs after wp-env destroy has destroyed the environment.
     */
    afterDestroy?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};

export interface WpEnvProperties {
  /**
   * The WordPress installation to use. If null is specified, wp-env will use the latest production release of WordPress.
   */
  core?: string | null;
  /**
   * The PHP version to use. If null is specified, wp-env will use the default version used with production release of WordPress.
   */
  phpVersion?: string | null;
  /**
   * A list of plugins to install and activate in the environment.
   */
  plugins?: string[];
  /**
   * A list of themes to install in the environment.
   */
  themes?: string[];
  /**
   * The primary port number to use for the installation. You'll access the instance through the port: http://localhost:8888
   */
  port?: number;
  /**
   * Mapping of wp-config.php constants to their desired values.
   */
  config?: {
    [k: string]: unknown;
  };
  /**
   * Mapping of WordPress directories to local directories to be mounted in the WordPress instance.
   */
  mappings?: {
    [k: string]: unknown;
  };
  /**
   * The port number to access phpMyAdmin.
   */
  phpmyadminPort?: number;
  /**
   * Whether to set up a multisite installation.
   */
  multisite?: boolean;
  [k: string]: unknown;
}
